version: '2'

services:
    db:
        restart: always
        image: mysql:5.7
        container_name: db
        volumes:
            - data:/var/lib/mysql
        ports:
            - 0.0.0.0:3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=mysql
            - MYSQL_USER=root
            - MYSQL_PASSWORD=mysql

volumes:
    data:
        driver: local
